name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 */12 * * *"   # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: Manthan283
          token: ${{ secrets.GH_TOKEN }}
          count_private: true
          include_all_commits: true
          theme: tokyonight

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update stats" || echo "No changes"
          git push
